// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ports/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/ports/ports.go -destination=internal/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	config "ProxyService2/internal/config"
	domain "ProxyService2/internal/domain"
	context "context"
	http "net/http"
	reflect "reflect"
	time "time"

	zerolog "github.com/rs/zerolog"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigStore is a mock of ConfigStore interface.
type MockConfigStore struct {
	ctrl     *gomock.Controller
	recorder *MockConfigStoreMockRecorder
	isgomock struct{}
}

// MockConfigStoreMockRecorder is the mock recorder for MockConfigStore.
type MockConfigStoreMockRecorder struct {
	mock *MockConfigStore
}

// NewMockConfigStore creates a new mock instance.
func NewMockConfigStore(ctrl *gomock.Controller) *MockConfigStore {
	mock := &MockConfigStore{ctrl: ctrl}
	mock.recorder = &MockConfigStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigStore) EXPECT() *MockConfigStoreMockRecorder {
	return m.recorder
}

// Current mocks base method.
func (m *MockConfigStore) Current() config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current")
	ret0, _ := ret[0].(config.Config)
	return ret0
}

// Current indicates an expected call of Current.
func (mr *MockConfigStoreMockRecorder) Current() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockConfigStore)(nil).Current))
}

// Subscribe mocks base method.
func (m *MockConfigStore) Subscribe(arg0 func(config.Config)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", arg0)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockConfigStoreMockRecorder) Subscribe(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockConfigStore)(nil).Subscribe), arg0)
}

// Update mocks base method.
func (m *MockConfigStore) Update(arg0 func(*config.Config) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockConfigStoreMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConfigStore)(nil).Update), arg0)
}

// Watch mocks base method.
func (m *MockConfigStore) Watch(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockConfigStoreMockRecorder) Watch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockConfigStore)(nil).Watch), arg0)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, fields map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", msg, fields)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), msg, fields)
}

// Info mocks base method.
func (m *MockLogger) Info(msg string, fields map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", msg, fields)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), msg, fields)
}

// Log mocks base method.
func (m *MockLogger) Log(level zerolog.Level, msg string, fields map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", level, msg, fields)
}

// Log indicates an expected call of Log.
func (mr *MockLoggerMockRecorder) Log(level, msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockLogger)(nil).Log), level, msg, fields)
}

// Warn mocks base method.
func (m *MockLogger) Warn(msg string, fields map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", msg, fields)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(msg, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), msg, fields)
}

// MockAccessService is a mock of AccessService interface.
type MockAccessService struct {
	ctrl     *gomock.Controller
	recorder *MockAccessServiceMockRecorder
	isgomock struct{}
}

// MockAccessServiceMockRecorder is the mock recorder for MockAccessService.
type MockAccessServiceMockRecorder struct {
	mock *MockAccessService
}

// NewMockAccessService creates a new mock instance.
func NewMockAccessService(ctrl *gomock.Controller) *MockAccessService {
	mock := &MockAccessService{ctrl: ctrl}
	mock.recorder = &MockAccessServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessService) EXPECT() *MockAccessServiceMockRecorder {
	return m.recorder
}

// ApplyConfig mocks base method.
func (m *MockAccessService) ApplyConfig(arg0 domain.AccessSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyConfig indicates an expected call of ApplyConfig.
func (mr *MockAccessServiceMockRecorder) ApplyConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyConfig", reflect.TypeOf((*MockAccessService)(nil).ApplyConfig), arg0)
}

// Check mocks base method.
func (m *MockAccessService) Check(ipValue, captchaValue string) domain.AccessDecision {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ipValue, captchaValue)
	ret0, _ := ret[0].(domain.AccessDecision)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockAccessServiceMockRecorder) Check(ipValue, captchaValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockAccessService)(nil).Check), ipValue, captchaValue)
}

// List mocks base method.
func (m *MockAccessService) List() []domain.AccessRule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]domain.AccessRule)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockAccessServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAccessService)(nil).List))
}

// Settings mocks base method.
func (m *MockAccessService) Settings() domain.AccessSettings {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Settings")
	ret0, _ := ret[0].(domain.AccessSettings)
	return ret0
}

// Settings indicates an expected call of Settings.
func (mr *MockAccessServiceMockRecorder) Settings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Settings", reflect.TypeOf((*MockAccessService)(nil).Settings))
}

// MockRateLimiter is a mock of RateLimiter interface.
type MockRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterMockRecorder
	isgomock struct{}
}

// MockRateLimiterMockRecorder is the mock recorder for MockRateLimiter.
type MockRateLimiterMockRecorder struct {
	mock *MockRateLimiter
}

// NewMockRateLimiter creates a new mock instance.
func NewMockRateLimiter(ctrl *gomock.Controller) *MockRateLimiter {
	mock := &MockRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiter) EXPECT() *MockRateLimiterMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockRateLimiter) Acquire(ip string, uploadHint int64, now time.Time) (*domain.RateLimitLease, *domain.RateLimitViolation) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ip, uploadHint, now)
	ret0, _ := ret[0].(*domain.RateLimitLease)
	ret1, _ := ret[1].(*domain.RateLimitViolation)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockRateLimiterMockRecorder) Acquire(ip, uploadHint, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockRateLimiter)(nil).Acquire), ip, uploadHint, now)
}

// Release mocks base method.
func (m *MockRateLimiter) Release(lease *domain.RateLimitLease, uploadedBytes, downloadedBytes int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release", lease, uploadedBytes, downloadedBytes)
}

// Release indicates an expected call of Release.
func (mr *MockRateLimiterMockRecorder) Release(lease, uploadedBytes, downloadedBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockRateLimiter)(nil).Release), lease, uploadedBytes, downloadedBytes)
}

// Settings mocks base method.
func (m *MockRateLimiter) Settings() domain.RateLimitSettings {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Settings")
	ret0, _ := ret[0].(domain.RateLimitSettings)
	return ret0
}

// Settings indicates an expected call of Settings.
func (mr *MockRateLimiterMockRecorder) Settings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Settings", reflect.TypeOf((*MockRateLimiter)(nil).Settings))
}

// TopViolators mocks base method.
func (m *MockRateLimiter) TopViolators(limit int) []domain.RateLimitViolation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopViolators", limit)
	ret0, _ := ret[0].([]domain.RateLimitViolation)
	return ret0
}

// TopViolators indicates an expected call of TopViolators.
func (mr *MockRateLimiterMockRecorder) TopViolators(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopViolators", reflect.TypeOf((*MockRateLimiter)(nil).TopViolators), limit)
}

// UpdateSettings mocks base method.
func (m *MockRateLimiter) UpdateSettings(arg0 domain.RateLimitSettings) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateSettings", arg0)
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockRateLimiterMockRecorder) UpdateSettings(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockRateLimiter)(nil).UpdateSettings), arg0)
}

// MockCacheService is a mock of CacheService interface.
type MockCacheService struct {
	ctrl     *gomock.Controller
	recorder *MockCacheServiceMockRecorder
	isgomock struct{}
}

// MockCacheServiceMockRecorder is the mock recorder for MockCacheService.
type MockCacheServiceMockRecorder struct {
	mock *MockCacheService
}

// NewMockCacheService creates a new mock instance.
func NewMockCacheService(ctrl *gomock.Controller) *MockCacheService {
	mock := &MockCacheService{ctrl: ctrl}
	mock.recorder = &MockCacheServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheService) EXPECT() *MockCacheServiceMockRecorder {
	return m.recorder
}

// BuildKey mocks base method.
func (m *MockCacheService) BuildKey(method, url string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildKey", method, url)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildKey indicates an expected call of BuildKey.
func (mr *MockCacheServiceMockRecorder) BuildKey(method, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildKey", reflect.TypeOf((*MockCacheService)(nil).BuildKey), method, url)
}

// Get mocks base method.
func (m *MockCacheService) Get(key string) (*domain.CachedResponse, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*domain.CachedResponse)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheServiceMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheService)(nil).Get), key)
}

// Invalidate mocks base method.
func (m *MockCacheService) Invalidate(req domain.CacheInvalidationRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockCacheServiceMockRecorder) Invalidate(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockCacheService)(nil).Invalidate), req)
}

// InvalidateAll mocks base method.
func (m *MockCacheService) InvalidateAll() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAll")
	ret0, _ := ret[0].(int)
	return ret0
}

// InvalidateAll indicates an expected call of InvalidateAll.
func (mr *MockCacheServiceMockRecorder) InvalidateAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAll", reflect.TypeOf((*MockCacheService)(nil).InvalidateAll))
}

// InvalidateForMutation mocks base method.
func (m *MockCacheService) InvalidateForMutation(path string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateForMutation", path)
	ret0, _ := ret[0].(int)
	return ret0
}

// InvalidateForMutation indicates an expected call of InvalidateForMutation.
func (mr *MockCacheServiceMockRecorder) InvalidateForMutation(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateForMutation", reflect.TypeOf((*MockCacheService)(nil).InvalidateForMutation), path)
}

// ShouldUse mocks base method.
func (m *MockCacheService) ShouldUse(host, path string, req *http.Request) (domain.CacheRule, bool, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldUse", host, path, req)
	ret0, _ := ret[0].(domain.CacheRule)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(string)
	return ret0, ret1, ret2
}

// ShouldUse indicates an expected call of ShouldUse.
func (mr *MockCacheServiceMockRecorder) ShouldUse(host, path, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldUse", reflect.TypeOf((*MockCacheService)(nil).ShouldUse), host, path, req)
}

// Snapshot mocks base method.
func (m *MockCacheService) Snapshot(limit int) domain.CacheSnapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", limit)
	ret0, _ := ret[0].(domain.CacheSnapshot)
	return ret0
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockCacheServiceMockRecorder) Snapshot(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockCacheService)(nil).Snapshot), limit)
}

// Store mocks base method.
func (m *MockCacheService) Store(host, path, key string, status int, header http.Header, body []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", host, path, key, status, header, body)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockCacheServiceMockRecorder) Store(host, path, key, status, header, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockCacheService)(nil).Store), host, path, key, status, header, body)
}

// UpdateSettings mocks base method.
func (m *MockCacheService) UpdateSettings(arg0 domain.CacheSettings) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateSettings", arg0)
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockCacheServiceMockRecorder) UpdateSettings(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockCacheService)(nil).UpdateSettings), arg0)
}

// MockObservabilityService is a mock of ObservabilityService interface.
type MockObservabilityService struct {
	ctrl     *gomock.Controller
	recorder *MockObservabilityServiceMockRecorder
	isgomock struct{}
}

// MockObservabilityServiceMockRecorder is the mock recorder for MockObservabilityService.
type MockObservabilityServiceMockRecorder struct {
	mock *MockObservabilityService
}

// NewMockObservabilityService creates a new mock instance.
func NewMockObservabilityService(ctrl *gomock.Controller) *MockObservabilityService {
	mock := &MockObservabilityService{ctrl: ctrl}
	mock.recorder = &MockObservabilityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObservabilityService) EXPECT() *MockObservabilityServiceMockRecorder {
	return m.recorder
}

// DecActive mocks base method.
func (m *MockObservabilityService) DecActive() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DecActive")
}

// DecActive indicates an expected call of DecActive.
func (mr *MockObservabilityServiceMockRecorder) DecActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecActive", reflect.TypeOf((*MockObservabilityService)(nil).DecActive))
}

// IncActive mocks base method.
func (m *MockObservabilityService) IncActive() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncActive")
}

// IncActive indicates an expected call of IncActive.
func (mr *MockObservabilityServiceMockRecorder) IncActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncActive", reflect.TypeOf((*MockObservabilityService)(nil).IncActive))
}

// Logs mocks base method.
func (m *MockObservabilityService) Logs(ip string, status, limit int) []domain.RequestLog {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ip, status, limit)
	ret0, _ := ret[0].([]domain.RequestLog)
	return ret0
}

// Logs indicates an expected call of Logs.
func (mr *MockObservabilityServiceMockRecorder) Logs(ip, status, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockObservabilityService)(nil).Logs), ip, status, limit)
}

// Monitoring mocks base method.
func (m *MockObservabilityService) Monitoring(topN int) domain.MonitoringSnapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Monitoring", topN)
	ret0, _ := ret[0].(domain.MonitoringSnapshot)
	return ret0
}

// Monitoring indicates an expected call of Monitoring.
func (mr *MockObservabilityServiceMockRecorder) Monitoring(topN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Monitoring", reflect.TypeOf((*MockObservabilityService)(nil).Monitoring), topN)
}

// Overview mocks base method.
func (m *MockObservabilityService) Overview() domain.DashboardOverview {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Overview")
	ret0, _ := ret[0].(domain.DashboardOverview)
	return ret0
}

// Overview indicates an expected call of Overview.
func (mr *MockObservabilityServiceMockRecorder) Overview() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Overview", reflect.TypeOf((*MockObservabilityService)(nil).Overview))
}

// Record mocks base method.
func (m *MockObservabilityService) Record(arg0 domain.RequestEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", arg0)
}

// Record indicates an expected call of Record.
func (mr *MockObservabilityServiceMockRecorder) Record(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockObservabilityService)(nil).Record), arg0)
}

// TopClients mocks base method.
func (m *MockObservabilityService) TopClients(limit int) []domain.TopClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopClients", limit)
	ret0, _ := ret[0].([]domain.TopClient)
	return ret0
}

// TopClients indicates an expected call of TopClients.
func (mr *MockObservabilityServiceMockRecorder) TopClients(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopClients", reflect.TypeOf((*MockObservabilityService)(nil).TopClients), limit)
}

// UpdateSettings mocks base method.
func (m *MockObservabilityService) UpdateSettings(arg0 domain.ObservabilitySettings) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateSettings", arg0)
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockObservabilityServiceMockRecorder) UpdateSettings(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockObservabilityService)(nil).UpdateSettings), arg0)
}

// UpdateUpstreamStatus mocks base method.
func (m *MockObservabilityService) UpdateUpstreamStatus(arg0 domain.UpstreamStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateUpstreamStatus", arg0)
}

// UpdateUpstreamStatus indicates an expected call of UpdateUpstreamStatus.
func (mr *MockObservabilityServiceMockRecorder) UpdateUpstreamStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUpstreamStatus", reflect.TypeOf((*MockObservabilityService)(nil).UpdateUpstreamStatus), arg0)
}

// UpstreamStatuses mocks base method.
func (m *MockObservabilityService) UpstreamStatuses() []domain.UpstreamStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpstreamStatuses")
	ret0, _ := ret[0].([]domain.UpstreamStatus)
	return ret0
}

// UpstreamStatuses indicates an expected call of UpstreamStatuses.
func (mr *MockObservabilityServiceMockRecorder) UpstreamStatuses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpstreamStatuses", reflect.TypeOf((*MockObservabilityService)(nil).UpstreamStatuses))
}
